### PR TITLE
Remove an email confirmation field from the feedback page

### PR DESCRIPTION
**Pull request by mybits**
PT: https://www.pivotaltracker.com/story/show/95038408

### CODE REVIEW

**Comment by otlaitil** [comment]
Looks good! :+1: There was no JS validations?

**Comment by mybits** [comment]
Surprisingly not:), only on email presence and format

**Comment by otlaitil** [comment]
I am blind :) Sorry. Ignore the previous comment.

**Comment by davidbasalla** [comment]
Looks good to me!

**Comment by h-lame** [comment]
:+1:

**Pull request merged**
