### PR TITLE
[elb_deployment_notification_hooks] Additional fixes for ELB deployment hooks

### PR DESCRIPTION
**Pull request by oskarpearson**
- Changed the name of the matched deployment group from Webservers to RailsAppServers,
  so that rollouts go to both Webservers and Background Job workers.
- Fixed some missing whitespace in bash commands that were causing syntax issues
- Fixed some problems with quoting in the imported AWS bash files that were
  being parsed by Ruby

Also:
- Added support for rolling out to a dev environment for testing
- Fixed a buglet where if the New Relic environment variable was not supplied,
  an error was displayed. This brings things in line with the Slack notifications.
- Added support for the dev environment

### CODE REVIEW

**Comment by oskarpearson** [comment]
Please note that:

* https://github.com/unboxed/e-petitions-deploy/pull/7 and this PR need to be merged in Tandem
* The stack probably needs to be updated after this set of changes
* Given the rename of the deployment group, you will need to follow the original steps in the deployment README to change the CodeDeploy setup - to add the two Auto Scaling groups and to change the name.

**Comment by oskarpearson** [comment]
This should fix the error 500s that happen during a code-deploy

**Comment by pixeltrix** [comment]
LGTM - I guess we need to wait for new stacks with workers before merging this?

**Comment by pixeltrix** [comment]
I've merged this into a local branch and will push up once I've rebuilt the preview stack

**Pull request closed without merging**
