### PR TITLE
Replay email address instead of confirming during create

### PR DESCRIPTION
**Pull request by h-lame**
For: https://www.pivotaltracker.com/story/show/94485374

1. Remove email_confirmation from creating and sigining a petition
2. Add a new step to the create process to replay the email address as the last step before submitting and allow the signer to make changes

Note: replaying the email while signing a petition will be dealt with in a future PR.

### CODE REVIEW

**Comment by mybits** [comment]
LGTM :palm_tree:

**Comment by otlaitil** [comment]
This staged implementation seems to work well and be easily extendable. Nice! :+1: LGTM.

**Comment by davidbasalla** [comment]
+1

**Comment by h-lame** [comment]
Rebased and will merge when green.

**Pull request merged**
