### PR TITLE
Quick change to archive show markup to allow petition steps to pass

### PR DESCRIPTION
**Pull request by alexander-bobin**

### CODE REVIEW

**Comment by mybits** [comment]
LGTM :palm_tree:

**Comment by yahoopete** [comment]
I'd be better to show something like the below:

"This petition was open between 21 March 2012 and 21 March 2013"

But happy to worry about this in a separate story if this is scope creep with this.....

**Comment by alexander-bobin** [comment]
Let's create a separate story for optimisations. This branch was really just to get the integration tests passing.

**Comment by yahoopete** [comment]
Fair enough.

**Pull request merged**
