### PR TITLE
Tidy up the alternate header

### PR DESCRIPTION
**Pull request by yahoopete**
:cry:

### CODE REVIEW

**Comment by pixeltrix** [comment]
You could also remove the cache key for `home_page` [here][1].

[1]: https://github.com/alphagov/e-petitions/blob/master/config/fragments.yml#L13-L14

**Comment by yahoopete** [comment]
@pixeltrix the whole header block, or just the keys?

header:
  keys:
    - :home_page
  options:
    expires_in: 300

**Comment by pixeltrix** [comment]
just the keys

**Comment by yahoopete** [comment]
Yeah, Travis told me that ;)  Ta

**Comment by yahoopete** [comment]
Caching issues resolved - good to go.

**Comment by henryhadlow** [comment]
Relevant https://github.com/alphagov/e-petitions/pull/319

**Pull request merged**
