### PR TITLE
Change 'Lists of petitions' to use a details elements

### PR DESCRIPTION
**Pull request by henryhadlow**

### CODE REVIEW

**Comment by henryhadlow** [comment]
Not sure how to fix these tests or why they are failing :unamused:

**Comment by yahoopete** [comment]
The tests are looking finding 2 instances of things like Rejected petition so don't know ow which one to select. 

It's messy.  X path constraints....  I had to hack a test script helper to tell it where to look for a similar problem. 

When I say "I",  I mean @h-lame

**Comment by h-lame** [comment]
Taking a look.

**Comment by h-lame** [comment]
Did a thing, should be green and mergable now.

**Comment by alexander-bobin** [comment]
LGTM

**Pull request merged**
