### PR TITLE
List debated petitions

### PR DESCRIPTION
**Pull request by alexander-bobin**
https://www.pivotaltracker.com/story/show/96658330

@h-lame, you may want to double check that our presumption that if a debate_outcome record exists for a petition than the petition has a debate outcome.

Also removed core.js as it's no longer needed

### CODE REVIEW

**Comment by h-lame** [comment]
Your assumption is correct.  Looks good to me!

**Comment by otlaitil** [comment]
:+1:

**Comment by davidbasalla** [comment]
looks good

**Comment by davidbasalla** [comment]
needs a rebase tho!

**Comment by alexander-bobin** [comment]
Rebased. Ready to merge when green

**Pull request merged**
