### PR TITLE
Email signatories with details of debate schedule

### PR DESCRIPTION
**Pull request by davidbasalla**
For https://www.pivotaltracker.com/story/show/96655906

Created the new job, mailer and updated the EmailSentReceipt and EmailRequestedReceipt models with the new 'debate_scheduled' fields. Using the same workflow as the previous debate_outcome implementation.

### CODE REVIEW

**Comment by h-lame** [comment]
Needs a rebase but this is pretty textbook.

**Comment by davidbasalla** [comment]
Rebased!

**Comment by otlaitil** [comment]
:+1: this needs reviewing and someone to merge it to master

**Comment by mybits** [comment]
LGTM :palm_tree:

**Pull request merged**
