### PR TITLE
Optional supporting details and rename Petition DB fields to match UI

### PR DESCRIPTION
**Pull request by h-lame**
For: https://www.pivotaltracker.com/story/show/97178596 and https://www.pivotaltracker.com/story/show/96647416 (yes I know it's bad form to do 2 stories in 1 PR sorry!)

This does touch many files so chances are this will either need hard rebasing as more things are merged in, or require other things to do lots of rebasing if they are merged in afterwards so we need to take some care.

### CODE REVIEW

**Comment by h-lame** [comment]
Oh, look at me not being consistent with my commit titles.  Oops.

**Comment by otlaitil** [comment]
:+1:

**Comment by davidbasalla** [comment]
Looks good! Out of curiosity, how did you go about doing the bulk renaming of fields?

**Comment by h-lame** [comment]
@davidbasalla nothing fancy: just find and replace in my editor + running the tests to see what I'd missed (searching for ``attribute:``, ``attribute =>``, ``:attribute``, ``.attribute`` rather than just ``attribute`` was useful for title as that is used in lots of places to mean other things).

**Comment by mybits** [comment]
:+1: :cake:

**Comment by h-lame** [comment]
I grow weary of rebasing this, can we merge if it goes green?

**Pull request merged**
