### PR TITLE
[Don't merge] Disable header link on homepage

### PR DESCRIPTION
**Pull request by henryhadlow**

### CODE REVIEW

**Comment by yahoopete** [comment]
Did you include those things @pixeltrix was suggesting?

**Comment by henryhadlow** [comment]
Nope I thought he was going to do that. Outside my expertise.

On 14 July 2015 at 18:11, Pete Herlihy <notifications@github.com> wrote:

> Did you include those things @pixeltrix was suggesting?
> On 14 Jul 2015 18:02, "Henry Hadlow" <notifications@github.com> wrote:
>
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/alphagov/e-petitions/pull/319
> > Commit Summary
> >
> > - Disable header link on homepage
> > - Add js to handle link edge-case
> >
> > File Changes
> >
> > - *A* app/assets/javascripts/homepage.js
> > <https://github.com/alphagov/e-petitions/pull/319/files#diff-0> (13)
> > - *M* app/assets/stylesheets/petitions/_header.scss
> > <https://github.com/alphagov/e-petitions/pull/319/files#diff-1> (6)
> > - *M* app/views/application/_header.html.erb
> > <https://github.com/alphagov/e-petitions/pull/319/files#diff-2> (10)
> > - *M* app/views/layouts/application.html.erb
> > <https://github.com/alphagov/e-petitions/pull/319/files#diff-3> (3)
> > - *M* config/initializers/assets.rb
> > <https://github.com/alphagov/e-petitions/pull/319/files#diff-4> (1)
> >
> > Patch Links:
> >
> > - https://github.com/alphagov/e-petitions/pull/319.patch
> > - https://github.com/alphagov/e-petitions/pull/319.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/alphagov/e-petitions/pull/319>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alphagov/e-petitions/pull/319#issuecomment-121311292>.
>



-- 
Henry Hadlow
Designer
Government Digital Service <https://gds.blog.gov.uk/>

**Comment by henryhadlow** [comment]
Yup OK waiting on @pixeltrix to optimise the js etc

**Comment by pixeltrix** [comment]
@henryhadlow @yahoopete updated for caching

**Comment by yahoopete** [comment]
LGTM

**Pull request merged**
