### PR TITLE
Move rare user actions from tabs to header

### PR DESCRIPTION
**Pull request by otlaitil**
For: https://www.pivotaltracker.com/n/projects/307301/stories/97014498

Move link to user profile, logout link and user management link
from tabnav to header. No styling or markup included.

### CODE REVIEW

**Comment by mybits** [comment]
LGTM :sunny:

**Comment by h-lame** [comment]
:+1: minor comment, but if no-one else feels strongly about it don't let that comment block merging.

**Comment by otlaitil** [comment]
@h-lame @alexander-bobin rebased & comments addressed (merge when green if happy?)

**Comment by otlaitil** [comment]
Build failed because of an unrelated spec, fixed in https://github.com/alphagov/e-petitions/pull/183

**Comment by otlaitil** [comment]
Fixed build, see the pervious comment. I'll buy a :beer: for the one who merges this.

**Comment by mybits** [comment]
No :beer: needed :)

**Pull request merged**
