### PR TITLE
Add government summary response

### PR DESCRIPTION
**Pull request by davidbasalla**
for https://www.pivotaltracker.com/story/show/96865276

... because it's Friday evening!

### CODE REVIEW

**Comment by h-lame** [comment]
Some minor comments, but this is good stuff.

**Comment by davidbasalla** [comment]
Have addressed all comments, thanks @h-lame!

**Comment by otlaitil** [comment]
LGTM! :+1:

**Comment by mybits** [comment]
needs :recycle:, looks good!

**Pull request merged**
